.gitignore
nodejs/client.js
nodejs/first-trace.js
nodejs/package.json
nodejs/server.js

I extracted these examples from the NodeJS getting started guide while reviewing it.

Add nodejs examples

---

all/Dockerfile
all/client.py
docker-compose.yml

The `demo-client` service acts as a client that queries all services (currently hardcoded in the client)

adding client to query all services

---

python/launcher/Dockerfile.client
python/launcher/Dockerfile.server
python/launcher/requirements.txt
python/opentelemetry/Dockerfile.client
python/opentelemetry/Dockerfile.server
python/opentelemetry/common.py
python/opentelemetry/requirements.txt
python/opentracing/Dockerfile.client
python/opentracing/Dockerfile.server
python/opentracing/client.py
python/opentracing/requirements.txt
python/opentracing/server.py
tools/integration/Dockerfile
tools/integration/requirements.txt

cleaning up some TODOs that are no longer needed with the latest release

update to latest version of otel python/launcher

---

Makefile
collector/rabbitmq/cmd/rabbitmq-simulator/go.mod
collector/rabbitmq/cmd/rabbitmq-simulator/go.sum
collector/rabbitmq/cmd/rabbitmq-simulator/rabbitmq-client.go
collector/rabbitmq/config.yaml
collector/rabbitmq/docker-compose.yaml
collector/rabbitmq/rabbitmq-leader.conf
collector/rabbitmq/rabbitmq-node-2.conf
collector/rabbitmq/rabbitmq-node-3.conf

Adds rabbitMQ example

---

collector/zookeeper/Makefile
collector/zookeeper/README.md
collector/zookeeper/collector.yml
collector/zookeeper/docker-compose.override.yml
collector/zookeeper/docker-compose.yml
collector/zookeeper/zoo.cfg

This PR adds an example integration environment of collecting Zookeeper metrics via the Prometheus Receiver.

Zookeeper prometheus

---

collector/elasticsearch/Makefile
collector/elasticsearch/collector.yml
collector/elasticsearch/docker-compose.override.yml

This PR helps address the issue to remove extras from examples as stated in #116.

Elasticsearch rm extras

---

collector/elasticsearch/collector.yml

requested by @carlos in Slack DM on June 30

add back logging exporter

---

collector/envoy/README.md

* Clarify the example is for metrics and traces

Update title for Envoy readme

---

collector/prom-native-nomad/README.md
collector/prom-native-nomad/collector.yml
collector/prom-native-nomad/docker-compose.yml
collector/prom-native-nomad/nomad/config/local.json

- Added Prom Native Hashicorp Nomad example

Added Prom Native Hashicorp Nomad example

---

collector/multi-project-collector/README.md
collector/multi-project-collector/config/collector.yml
collector/multi-project-collector/docker-compose.yml

* Adds example for using a single collector with multiple Lightstep projects.

Add multi-project example

---

collector/k8s-tracing/apiserver-tracing.yaml
collector/k8s-tracing/containerd.toml
collector/k8s-tracing/crio.conf
collector/k8s-tracing/docker-compose.yml
collector/k8s-tracing/kubelet-tracing.yaml
collector/k8s-tracing/otel-collector-config.yaml
collector/k8s-tracing/readme.md
collector/k8s-tracing/run-minikube.sh

* Example of Kubernetes with experimental tracing features enabled.

Add k8s experimental tracing demo

---

operator/java-autoinst/readme.md
operator/java-autoinst/values.yaml

* Adds example for using the collector operator to auto-instrument a Java

Add Example for Java Auto-Instrumentation

---

operator/java-autoinst/readme.md

Let me know if there are any questions!

Minor updates to java-autoinst readme

---

collector/nginx-ingresscontroller/Makefile

Fix nginx ingress controller example

---

collector/nginx-ingresscontroller/Makefile

Fix otel collector check in nginx ingress example

---

collector/mysql/docker-compose.yml
collector/postgres/docker-compose.yml

Bump otel version to 0.74.0 for postgresql & mysql

---

collector/vanilla/collector.yaml

Adding metrics to the generic config

add metrics to vanilla collector config

---

.github/workflows/update-containers.yml

Removes shim containers from hourly action to update them.
We removed the code underlying these containers.
***

Fix build - remove app containers

---

collector/vanilla/collector.yaml

Add back batch processor

---

collector/prom-native-arangodb/README.md
collector/prom-native-arangodb/arangodb.conf
collector/prom-native-arangodb/collector.yml
collector/prom-native-arangodb/docker-compose.yml

Adds ArangoDB example
Extend coverage of Collector integrations
***

Add arangodb with prom-native metrics

---

collector/couchdb/README.md
collector/couchdb/collector.yml
collector/couchdb/docker-compose.cluster.yml
collector/couchdb/docker-compose.yml

Adds a CouchDB example.
Expand coverage of Lightstep integrations of OTel Collector receivers.
***
@hecomp @altuner @heydbut

Add CouchDB example

---

collector/fluentd/README.md
collector/fluentd/collector-configmap.yaml
collector/fluentd/collector.yaml
collector/fluentd/fluentd-configmap.yaml
collector/fluentd/fluentd-rbac.yaml
collector/fluentd/fluentd.yaml

fluentd example

---

collector/istio/Dockerfile
collector/istio/README.md
collector/istio/go-istio-demo.yaml
collector/istio/go.mod
collector/istio/istio-operator.yaml
collector/istio/kind-config.yaml
collector/istio/lightstep-secret.yaml
collector/istio/main.go
collector/istio/otel-collector-config.yaml
collector/istio/otel-collector-configmap.yaml
collector/istio/otel-collector-deployment.yaml
collector/istio/otel-collector-rbac.yaml
collector/istio/otel-collector-service.yaml

added istio k8s demo

---

collector/activedirectoryds/collector.yaml
collector/activedirectoryds/docker-compose.yaml
collector/activedirectoryds/docker-compose2.yaml
collector/activedirectoryds/docker-composeV2.yaml

Added Otel collector activedirectoryds
***

otel collector activedirectoryds

---

collector/airflow/README.md
collector/airflow/collector.yml
collector/airflow/docker-compose.yml

Airflow example

---

.github/PULL_REQUEST_TEMPLATE.md

Adding checklist to the PR template 
***

adding PR checklist

---

collector/prom-native-clickhouse/collector.yml
collector/prom-native-cockroachdb/collector.yml

Fix endpoints for clickhouse & cockroachdb

---

collector/prom-native-singlestore/README.md
collector/prom-native-singlestore/collector.yml
collector/prom-native-singlestore/docker-compose.yml
collector/prom-native-singlestore/init.sql

Add SignleStore DB example
To start its integration with LS.
***

Add singlestore example

---

collector/aws-eks/lightstep-values.yaml
collector/aws-eks/readme.md

Adds instructions/demo for getting metrics from EKS clusters in EKS.

Add instructions for AWS EKS

---

collector/prom-native-scylla/README.md
collector/prom-native-scylla/collector.yaml
collector/prom-native-scylla/docker-compose.yaml

Description is not provided for all metrics, so it may be blank. Attributes are also not always provided. When there are multiple attributes on a metric reord they should be space separated.

added scylla prom example

---

collector/gitea/README.md
collector/gitea/app.ini
collector/gitea/collector.yaml
collector/gitea/docker-compose.yaml

Description is not provided for all metrics, so it may be blank. Attributes are also not always provided. When there are multiple attributes on a metric reord they should be space separated.

Add gitea example

---

collector/grafana/README.md
collector/grafana/collector.yaml
collector/grafana/docker-compose.yaml
collector/grafana/grafana.ini
collector/grafana/prometheus/prometheus.yml
collector/grafana/provisioning/dashboards/default.yaml
collector/grafana/provisioning/dashboards/demo-dashboard.json
collector/grafana/provisioning/dashboards/grafana-internals.json
collector/grafana/provisioning/datasources/default.yaml

Description is not provided for all metrics, so it may be blank. Attributes are also not always provided. When there are multiple attributes on a metric reord they should be space separated.

Add grafana example

---

collector/docker/dockerstats/Dockerfile
collector/docker/dockerstats/README.md
collector/docker/dockerstats/collector.yml
collector/docker/dockerstats/docker-compose.yml
collector/docker/dockerstats/metrics.csv

Fixed docker stats example
Description is not provided for all metrics, so it may be blank. Attributes are also not always provided. When there are multiple attributes on a metric reord they should be space separated.

Docker stats example fix

---

collector/httpcheck/docker-compose.yml
collector/ibmmq/collector.yaml
collector/ibmmq/docker-compose.yaml

- Modified httpcheck ibmmq otel version
- [] Each example contains a README file.
- [] README documents all steps and variables required to run the example. The simplest way to confirm this is to follow the instructions on a clean machine.
- [] README file contains the links to the official documentation with relevant configuration and to the metrics published if that is available.
- [] Used images of apps and collectors have to be pinned, "latest" should never be used.
- [] Evidences with screenshots provided from the reviewer.
- [] Includes a file called `metrics.csv` with metrics produced by the example.
Description is not provided for all …

modified httpcheck ibmmq otel version
